### ISSUE TITLE
Another display issue in reports

### ISSUE THREAD

**Issue by SUBnet192** [EvotecIT/Testimo#154]
All tests failed except one informational. That shouldn't make it a "passed" test.

![image](https://user-images.githubusercontent.com/11916348/144431059-e38a5f49-6b84-422b-a446-7cae663c17a3.png)

**Comment by PrzemyslawKlys** [comment]
It's already fixed in #149 

![image](https://user-images.githubusercontent.com/15063294/144476754-f093db16-772b-452b-9cfd-04198b410132.png)

It was showing that because the original display Testimo only supported True/False/$null 
True = Passed, False = Failed, $null - Skipped

This was the same for the interface and HTML. 

New version supported scale in assessment, importance and so on where True/False/$null can have different value for assessment. This was fixed for Table, but never for chart, and console.

Now it's also fixed for charts and for console

![image](https://user-images.githubusercontent.com/15063294/144477056-3cdb7e63-5ad8-4793-bf80-41a87aebbba3.png)
