### ISSUE TITLE
New install not adding all dependencies

### ISSUE THREAD

**Issue by dzampino** [EvotecIT/Testimo#164]
After installing Testimo using `Install-Module -Name Testimo -Force -AllowClobber` and running `Invoke-Testimo` I received an error that `Write-Color` wasn't a function. After reviewing the installed modules, and checking the PowerShell gallery dependencies for Testimo, it looks like the following modules (according to README) are not dependencies: PSWinDocumentation.AD, PSWriteColor, Connectimo, and Emailimo.

**Comment by PrzemyslawKlys** [comment]
Actually, the only thing that's missing is Write-Color which is from PSWriteColor. PSWriteColor used to be in required modules in PSSharedGoods, along with Connectimo. But I now merge write-color in, 

![image](https://user-images.githubusercontent.com/15063294/173110442-fb99c0f1-d4af-4a7e-8493-c2b74ff3d5a1.png)
![image](https://user-images.githubusercontent.com/15063294/173110481-a2beb214-8746-4555-82c2-6ab46d932217.png)
![image](https://user-images.githubusercontent.com/15063294/173110515-8fae1a0a-0acb-40ba-ab3b-5715231041ad.png)

I'll fix PSWriteColor as part of Testimo. I don't think we need Connectimo or Emailimo. PSWindocumentation.AD - I am not sure. I guess not, because I moved required functions into ADEssentials.

**Comment by dzampino** [comment]
Do you still need DSInternals? I know that it's currently a dependency for PSWinDocumentation.AD.

**Comment by PrzemyslawKlys** [comment]
I don't think at this moment nothing in Testimo uses DSInternals. But there was an idea to use it in some tests.
