### ISSUE TITLE
Typos :)

### ISSUE THREAD

**Issue by SUBnet192** [EvotecIT/Testimo#98]
Net Session Enumaration --> should be enumeration

**Comment by PrzemyslawKlys** [comment]
Have you considered doing PR's? It's really easy and I would appreciate help with basic stuff and if you have time for some advanced fixing - even better.

**Comment by SUBnet192** [comment]
Sure could. Didn't think you wanted people to mess around with your code.

**Comment by PrzemyslawKlys** [comment]
You need to fork it. Once you fork it you modify your own copy in your own branch. Once happy you create pull request and delete branch. 

Fixing typos, adding descriptions, texts and other stuff is even doable online in the browser. Just press edit and fix it it will lead you. 

I am posting all my stuff on GitHub to share but also benefit from knowledge of others. I a don't want to do it myself - otherwise my 40projects will soon die out.

**Comment by SUBnet192** [comment]
No problems. Will give that a try :)

**Comment by PrzemyslawKlys** [comment]
Issue is still valid ;)

**Comment by SUBnet192** [comment]
Fixed in the latest merge you did.
